### PR TITLE
Fix for quiz that needs grading not properly retrieved

### PR DESCRIPTION
**Pull request by mouneyrac**
Hi guys,
thanks for maintaining this great plugin. It was easy to read even though I have little knowledge of the quiz code. It would be a nice feature to have in Moodle core, it makes sense to me that every teachers want to know what they need to grade without browsing everywhere.

The current quiz SQL request doesn't work on postgres (GROUP BY error) + it looks like it is broken to me. For example there is a questionattemptid == quizattemptid.

As I am not keen with big SQL request containing different JOIN, SUBSELECT, MAX etc... I had a look to Tim Hunt's student grading report for quiz (in Moodle.org plugin repository) which retrieves the quiz attempts that need to be graded. 

I created this pull request for you to be alerted as the Github issue tracker is not enabled.  Obviously this pull request is more serving of bug report, you don't want to merge it in this state as it doesn't "fit" with the coding of this plugin.

Thanks again,
Jerome

### CODE REVIEW

**Comment by mouneyrac** [comment]
I added a second commit that expand/collapse the course title.

**Comment by mouneyrac** [comment]
I added a third commit with a collaspe/expand all button.

**Comment by remotelearner** [comment]
I'm leaning towards rejecting the lesson plugin because it's dependent on the grade permission for lesson which doesn't exist.  It's currently triggering a notice in my test environment:

Capability "mod/lesson:grade" was not found! This has to be fixed in code.
    line 389 of /lib/accesslib.php: call to debugging()
    line 33 of /blocks/grade_me/lib.php: call to has_capability()
    line 95 of /blocks/grade_me/block_grade_me.php: call to block_grade_me_get_course_gradeables()
    line 294 of /blocks/moodleblock.class.php: call to block_grade_me->get_content()
    line 236 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
    line 993 of /lib/blocklib.php: call to block_base->get_content_for_output()
    line 1045 of /lib/blocklib.php: call to block_manager->create_block_contents()
    line 361 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
    line 45 of /theme/clean/layout/columns3.php: call to core_renderer->standard_head_html()
    line 877 of /lib/outputrenderers.php: call to include()
    line 807 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 245 of /course/view.php: call to core_renderer->header()

**Comment by tbannister** [comment]
Hi Jerome, during Testing I found that the cache wasn't refreshing properly when the cron was run.  When my second test user submitted an assignment (assign) and a quiz they didn't show up after the cron was run, although they did show up in the grading view for the assign module and quiz module.

**Comment by mouneyrac** [comment]
Yes there are some bugs I am aware of. The pull request of my master branch as nothing to do anymore with my originally pull. The code logic started to change quit a bit from grade_me and I integrated few fixes from AL. I was not expecting pull request to works that way. Initially I thought pull request only kept the commits at the time of the pull request. Then as there were not much activity on the rep I thought the pull request didn't matter. I'll close this pull request as its too messy now. The only commits you may want to have a look is the collapse/expand ones. Cheers, jerome.

**Comment by tbannister** [comment]
I think the pull request is just a pointer to a branch, so any updates added to the pull request branch get included in the pull request.

Thanks for the submission, anyway, I'm using the fixes for the quiz, forum and glossary links, and the jQuery fix.  The expand/collapse changes have already been included in the plugin.

**Pull request closed without merging**
